//! lava-akeyless — autogenerated typed resource catalog for the
//! akeyless terraform provider. Mirrors pangea-akeyless.

#![allow(clippy::module_name_repetitions)]

pub const RESOURCES_DIR: &str = "resources";

pub const RESOURCES: &[&str] = &[
    "akeyless_auth_method_api_key",
    "akeyless_auth_method_aws_iam",
    "akeyless_auth_method_k8s",
    "akeyless_dynamic_secret_aws",
    "akeyless_pki_cert_issuer",
    "akeyless_role",
    "akeyless_static_secret",
    "akeyless_target_aws",
    "akeyless_target_db",
    "akeyless_target_k8s",];

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn every_registered_resource_has_a_tlisp_file() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        for name in RESOURCES {
            let p = base.join(format!("{name}.tlisp"));
            assert!(p.exists(), "missing typed shape on disk: {}", p.display());
        }
    }
    #[test]
    fn index_tlisp_exists() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        assert!(base.join("_index.tlisp").exists());
    }
    #[test]
    fn schema_json_present() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        assert!(base.join("schema.json").exists());
    }
    #[test]
    fn at_least_one_resource_registered() {
        assert!(!RESOURCES.is_empty());
    }
}
